[package]
name = "cryptoquip_2"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
pdf = "0.9.0"
png = "0.17.16"
reqwest = { version = "0.12.15", features = ["blocking"] }
scraper = "0.23.1"

[features]
cache = []